### ISSUE TITLE
Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library

### ISSUE THREAD

**Issue by NagaChiang** [r0adkll/upload-google-play#129]
## Description

I encountered the error as title:

```
Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library
```

### Failed Attempts

- GitHub Action Ubuntu versions
  - 20.04
  - 22.04
  - 24.04
- Workaround: `export OPENSSL_CONF=/dev/null`

### Reference

- https://github.com/bazelbuild/rules_closure/issues/351

## Workflow Step Configuration

```yml
- name: Deploy App to Google Play internal track
  if: ${{ startsWith(github.ref, 'refs/tags/') }}
  uses: r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
    packageName: com.example.app
    track: internal
    releaseFiles: build/app/outputs/bundle/release/app-release.aab
```

## Step Debugging

- [x] I have enabled [Step Debug Logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)

```
Run r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ***
    packageName: ***
    track: internal
    releaseFiles: build/app/outputs/bundle/release/app-release.aab
    inAppUpdatePriority: 0
/usr/bin/docker exec  97e64bd37f08b044e9f03cbacc8240862f90362a3eea25aae298815f6382b918 sh -c "cat /etc/*release | grep ^ID"
##[debug]ID=ubuntu
##[debug]ID_LIKE=debian
##[debug]Running JavaScript Action with default external tool: node12
##[debug]Finding files build/app/outputs/bundle/release/app-release.aab
Creating a new Edit for this release
Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library
##[debug]Node Action run completed with exit code 1
##[debug]GOOGLE_APPLICATION_CREDENTIALS='./serviceAccountJson.json'
##[debug]Finishing: Deploy App to Google Play internal track
```

**Comment by boswelja** [comment]
This seems like an issue with some of the runner OSes. Is there a fix we can implement on the actions side?

**Comment by NagaChiang** [comment]
From what I Googled, I agree with you that it's something related to the runner OS. But sorry I'm not familiar with the tech stack it uses, also I don't know what problem it actually happens.

I tried `ubuntu-latest` this week, but still no luck.

Thank you!

**Comment by NagaChiang** [comment]
> Can you elaborate on how you fixed this issue with the described workaround? @NagaChiang `export OPENSSL_CONF=/dev/null `
> 
> I tried to run this command as a step in the GitHub Action, but this doesn't seem to work.

Oh sorry to confuse you, I meant I tried that but not work either.

**Comment by boswelja** [comment]
Seems like this was patched in node.js, hopefully Actions runners were updated and we will no longer see it here :)
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1979639

**Comment by pdeveltere** [comment]
This seems to be a problem for us as well. @NagaChiang @bschmalbSP any updates on how you solved this?

**Comment by pdeveltere** [comment]
@r0adkll I think you could fix this for us by adding `export OPENSSL_CONF=/dev/null` to your code. What would also solve it is setting the node version of this github action to node18

**Comment by boswelja** [comment]
> @r0adkll I think you could fix this for us by adding `export OPENSSL_CONF=/dev/null` to your code. What would also solve it is setting the node version of this github action to node18
> 

Please make sure you are using the latest Action version (NOT v1), as the latest version should be running ok the latest Node version.

**Comment by pdeveltere** [comment]
@boswelja thanks for the quick response. We set it to v1.0.19 and the issue still persisted. When specifying v1, the latest v1 version is automatically downloaded (v1.0.19), so that is not the issue.

**Comment by pdeveltere** [comment]
@boswelja ok, what do you mean the next release? the next release of this github action? 

> That aside, I will look at bumping our node version 🙂

I looking into that as well. I forked this action and was thinking of setting the nodejs version to 18. but it's not possible. Apparently only v16 is supported. It's a bit confusing since in their package.json the `@types/node` are set to `18`: https://github.com/actions/typescript-action/blob/main/package.json. But the version of node is still `nodejs16`: https://github.com/actions/typescript-action/blob/main/action.yml

**Comment by boswelja** [comment]
> @boswelja ok, what do you mean the next release? the next release of this github action?
> 
> > That aside, I will look at bumping our node version 🙂
> 
> I looking into that as well. I forked this action and was thinking of setting the nodejs version to 18. but it's not possible. Apparently only v16 is supported. It's a bit confusing since in their package.json the `@types/node` are set to `18`: https://github.com/actions/typescript-action/blob/main/package.json. But the version of node is still `nodejs16`: https://github.com/actions/typescript-action/blob/main/action.yml

Yep, the next release of the action. I'm hesitant to add code to the action to work around bugs that are supposedly fixed (plus it seems like it's fixed for the others too - based on their lack of response).

According to [this discussion on Node JS](https://github.com/nodejs/node/discussions/43184), it should be fixed in 16.16.x. It's probable that the 22.04 runners have updated to this version, I encourage you to do the same :)

**Comment by svendroid** [comment]
Sorry for posting on the closed thread, but I am experiencing the same issue.

I have following config:

```
jobs:
  assembleRelease:
    runs-on: ubuntu-22.04

    container:
      image: cirrusci/flutter:3.3.6

...

      - name: Upload to GooglePlay
        uses: r0adkll/upload-google-play@v1.0.19
```

The container image also uses Ubuntu 22.04 LTS.
I also tried running `export OPENSSL_CONF=/dev/null` but this did not fix it for me. I just executed it in a step like this:
```
- name: workarround
        run: export OPENSSL_CONF=/dev/null
```
How did you apply the `export OPENSSL_CONF=/dev/null` workarround to fix it?

see https://github.com/MunichWays/munich-ways-app/blob/master/.github/workflows/android-release.yml for workflow and failed job here https://github.com/MunichWays/munich-ways-app/actions/runs/3504557103/jobs/5870309911

**Comment by cosnomi** [comment]
I've got the workaround actually work by setting env within the step.

```yaml
- uses: r0adkll/upload-google-play@974d2d75669a518d2ed54462020437841e2745a4
  env:
    OPENSSL_CONF: /dev/null
  with:
    packageName: com.example
    # ...
```
